// src/constants/activity.js

export const ACTIVITY_EVENTS = Object.freeze({
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",

  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",

  FILE_UPLOADED: "FILE_UPLOADED",

  PROFILE_UPDATED: "PROFILE_UPDATED",
});

export const ENTITY_TYPES = Object.freeze({
  PROJECT: "Project",
  TASK: "Task",
  USER: "User",
});